# This file configures funding links for your project.

github: TabbedOutWiki
patreon: # TODO: Update with specific account
ko_fi: # TODO: Update with specific account
open_collective: # TODO
custom:
  - url: https://tabbedoutwiki.gg/support # Replace with a custom support page URL
    label: Support TabbedOutWiki
