globs:
  - "**/*.md"
ignores:
  - 'node_modules/**'
  - 'public/**'
  - 'tmp/**'

# https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#rules--aliases
config:
  MD001: true
  MD003:
    style: atx
  MD004:
    style: dash
  MD005: true
  MD007: false # if enabled, throws errors when definition descriptions contain list items
  MD009: true
  MD010: true
  MD011: true
  MD012: true
  MD013: false
  MD014: true
  MD018: true
  MD019: true
  MD020: true
  MD021: true
  MD022: true
  MD023: true
  MD024: true
  MD025: true
  MD026: true
  MD027: true
  MD028: false
  MD029:
    style: one
  MD030: true
  MD031: true
  MD032: true
  MD033: true
  MD034: true # Uncertain
  MD035:
    style: ---
  MD036: true
  MD037: true
  MD038: true
  MD039: true
  MD040: true
  MD041: false
  MD042: true
  MD043: false
  MD044: false
  MD045: true
  MD046:
    style: fenced
  MD047: true
  MD048:
    style: backtick
  MD049:
    style: asterisk
  MD050:
    style: asterisk
  MD051: false # Uncertain
  MD052: true
  MD053: true
  MD054:
    autolink: true
    collapsed: true
    full: true
    inline: true
    shortcut: true
    url_inline: false
  MD055:
    style: consistent
  MD056: true
  MD058: true
  MD059:
    prohibited_texts:
      - click here
      - here
      - link
      - more
  MD060: false # Uncertain
